"""empty message

Revision ID: 8d41116605c6
Revises: 
Create Date: 2019-06-26 13:05:05.360018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d41116605c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_form_step1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('street_adress', sa.String(length=120), nullable=False),
    sa.Column('code_city', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('mobil_phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('social_security', sa.Integer(), nullable=False),
    sa.Column('driver_license', sa.Integer(), nullable=False),
    sa.Column('issuing_state', sa.String(length=80), nullable=False),
    sa.Column('home_ownership', sa.String(length=80), nullable=False),
    sa.Column('time_at_residence', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('code_city'),
    sa.UniqueConstraint('driver_license'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('home_ownership'),
    sa.UniqueConstraint('issuing_state'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('mobil_phone'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('social_security'),
    sa.UniqueConstraint('street_adress'),
    sa.UniqueConstraint('time_at_residence'),
    sa.UniqueConstraint('zip')
    )
    op.create_table('long_form_step2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('military', sa.String(length=10), nullable=False),
    sa.Column('income', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('work_phone', sa.Integer(), nullable=False),
    sa.Column('time_of_job', sa.String(length=10), nullable=False),
    sa.Column('total_monthly_income', sa.String(length=80), nullable=False),
    sa.Column('payment_frequency', sa.String(length=20), nullable=False),
    sa.Column('first_payment', sa.Date(), nullable=True),
    sa.Column('second_payment', sa.Date(), nullable=True),
    sa.Column('deposit', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('deposit'),
    sa.UniqueConstraint('income'),
    sa.UniqueConstraint('military'),
    sa.UniqueConstraint('payment_frequency'),
    sa.UniqueConstraint('position'),
    sa.UniqueConstraint('time_of_job'),
    sa.UniqueConstraint('total_monthly_income'),
    sa.UniqueConstraint('work_phone')
    )
    op.create_table('long_form_step3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aba', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=10), nullable=False),
    sa.Column('time_at_bank', sa.String(length=10), nullable=False),
    sa.Column('checking', sa.String(length=10), nullable=False),
    sa.Column('checking_account', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aba'),
    sa.UniqueConstraint('bank_name'),
    sa.UniqueConstraint('checking'),
    sa.UniqueConstraint('checking_account'),
    sa.UniqueConstraint('time_at_bank')
    )
    op.create_table('short_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('last_4_of_ssn', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('last_4_of_ssn'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('zip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_form')
    op.drop_table('long_form_step3')
    op.drop_table('long_form_step2')
    op.drop_table('long_form_step1')
    # ### end Alembic commands ###
